set nocompatible              " be iMproved
filetype off                  " required!

call plug#begin('~/.vim/plugged')


" My bundles here:
Plug 'kien/ctrlp.vim'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-bundler'
Plug 'gregsexton/MatchTag'
Plug 'vim-ruby/vim-ruby'
Plug 'slim-template/vim-slim.git'

" Vim snippets
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'closetag.vim'

" Vim tabular
Plug 'godlygeek/tabular'

" Markdown
Plug 'plasticboy/vim-markdown'
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_frontmatter = 1

Plug 'slim-template/vim-slim'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'bling/vim-bufferline'

" Comment blocks
Plug 'tomtom/tcomment_vim'

" Manage ( [ ' "
Plug 'tpope/vim-surround'

" Jump to matching HTML tag.
Plug 'vim-scripts/matchit.zip'

" filetypes
Plug 'kchmck/vim-coffee-script'
Plug 'ekalinin/Dockerfile.vim'

" Add plugins to &runtimepath
call plug#end()

filetype plugin indent on     " required!

" Vim airline always
set laststatus=2

" Highlight syntax
syntax on

" Set colorscheme to wwdc_2016
colorscheme wwdc_2016
hi Normal ctermbg=none
hi LineNr ctermfg=grey
" Set vim-airline theme
let g:airline_theme='base16_default'

" Highlight search results
set hlsearch


set number
set relativenumber

set expandtab
set smarttab
set shiftwidth=2 " Number of spaces used in auto-indentation.
set tabstop=2 " A tab is equal to 2 spaces. Coding practice for ruby.

set autoindent
set smartindent

let html_no_rendering=1
set clipboard=unnamed

" Highlight current line
set cursorline 
